--- #YAML:1.0
name:                Template-Plugin-Dump
version:             0.01
abstract:            alternative dumper plugin with Data::Dump
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Data::Dump:                    0
    Template:                      0
    Test::UseAllModules:           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
